### ISSUE TITLE
How to access terminal as seen in Readme.md 

### ISSUE THREAD

**Issue by Lukas1h** [ea/bosch_headunit_root#26]
At the beginning of the Readme, it displays an image of the headunit running a terminal. How was this done? Was this the result of changing the boot prams? I could not find a reference to it in any of the docs. Thanks!

**Comment by ea** [comment]
While testing stuff, I've replaced the node code that usually displays the "Apps" page in settings with a script that would run commands and display those. It wasn't interactive as there's no keyboard. 

I didn't find an easy way to script display access otherwise , though there are some sample/demo programs that output directly to display in /opt and /bin. I always wanted to retain the existing UI and just hook into it as needed , so I didn't spend too much time digging into display management. Suffice it to say , it doesn't expose the usual framebuffer and isn't running X or anything of the sort, it's more complicated.

**Comment by Lukas1h** [comment]
Thats what I thought, seeing that the notification bar was still there. I tried to access the framebuffer but had no luck. Right now I don't have an ethernet adapter, but I was thinking to look at `/dev/uinput` or `dev/input/` or maybe something like `/proc/keypad/` and see if it would be possible to get button presses (if it even exists). Not too experienced with reverse engineering, besides hacking a few kindles. BTW, I was messing around with the Node.js server and found that the `<video>` tag works and even has a nice snazzy UI with volume control. I might try to get some videos to play. Maybe even mount a USB DVD drive and display them. ;)
