### ISSUE TITLE
Found Continuity

### ISSUE THREAD

**Issue by rempeldev** [ea/bosch_headunit_root#3]
![Inked06_mainboard (1)_LI](https://user-images.githubusercontent.com/78399486/106690871-62f2c600-6587-11eb-916f-339fc9c720ac.jpg)
On one of my units, I was probing Tx Rx around the board, found continuity to the harness connector. Marked out in the picture according to the colour of wire you used. Looks like the physical connector has those pins really short so they don't actually plug into the vehicles harness.

**Comment by ea** [comment]
Ah, i see what you mean. Nice find!
 I traced the signals to unpopulated debug headers and didn't check further. 
Decided to solder onto nearby test pads instead of header pads because they were bigger targets. 

 Those two pins on the harness look like they've been intentionally clipped, but would definitely make it easier to access the console.
